# Generated by Django 5.1.2 on 2024-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_video_num_likes_alter_video_num_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoslug',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Vídeo'),
        ),
    ]
